all:
	g++ -std=c++11 chat_server.cpp -o chat_server -lboost_system
	g++ -std=c++11 chat_client.cpp -o chat_client -lboost_system -pthread
server:
	g++ -std=c++11 chat_server.cpp -o chat_server -lboost_system
client:
	g++ -std=c++11 chat_client.cpp -o chat_client -lboost_system -pthread
